### ISSUE TITLE
2 missing iDEAL issuers

### ISSUE THREAD

**Issue by basst85** [wirecard/woocommerce-ee#138]
### Issue

**Problem description:**
There are missing 2 iDEAL issuers in class-wc-gateway-wirecard-ideal.php
Missing banks: "Moneyou" and "Svenska Handelsbanken"

Check this page for a recent list: https://www.ideal.nl/en/partners/issuers/

**Comment by basst85** [comment]
Thanks @rinnhofer 👍🏻

**Comment by rinnhofer** [comment]
@basst85 The missing iDEAL issuers are now available in the latest release.

https://github.com/wirecard/woocommerce-ee/releases/tag/1.6.1

Kind regards,
Wirecard Pluginteam
