### ISSUE TITLE
Wirecard payment page redirection for credit cards

### ISSUE THREAD

**Issue by EranKT** [wirecard/woocommerce-ee#185]
### Prerequisites

- [ v] I have my [server set up correctly](https://github.com/wirecard/woocommerce-ee/wiki/Installation#requirements).
- [v ] I am using a [supported version of WooCommerce](https://github.com/wirecard/woocommerce-ee/wiki#download-wirecard-woocommerce-extension).

### Versions

**WooCommerce version:** 4.9.9 
**PHP version:** ...  

### Issue
HPP option

**Problem description:**
I saw that exist a seperate Seemless plugin for WooCommerce.
I was expecting that in this extension plugin would be the Hosted Payment Page (HPP) method.

**Steps to reproduce:**
https://document-center.wirecard.com/pages/viewpage.action?pageId=786859

Are you planning to add this feature to this plugin?
If not, can you please direct me to where I can find a plugin that include this feature?

Thanks,

**Comment by hbrandl** [comment]
Hi,

to be able to answer which Extension is the best one for you I would need to know which Gateway you are using.

This Extension is for the Wirecard Payment Processing Gateway and uses the seamless mode of the payment page core credit cards to ensure you are SAQ-A compliant. For this Extension we have currently no plans to add a hosted payment page.

If you bought the product Wirecard Checkout Seamless you can use this extension:
https://github.com/wirecard/woocommerce-wcs

If you bought the product Wirecard Checkout Page you can use this extension:
https://github.com/wirecard/woocommerce-wcp

Hope that helps. Feel free to reopen in case you have additional questions.

Kind regards,
Hartwig
