### ISSUE TITLE
method_name property does not exist in WC

### ISSUE THREAD

**Issue by szepeviktor** [wirecard/woocommerce-ee#209]
See https://docs.woocommerce.com/wc-apidocs/class-WC_Payment_Gateway.html

| WC | WireCard | purpose |
| - | - | - |
| title | method_title | heading on the UI |
| method_title | method_name | machine name |

I think we are misusing these two.

**Comment by serucee** [comment]
Hi,

thank you for your input. When looking at the documentation at https://docs.woocommerce.com/document/payment-gateway-api/#section-3 you can see that method_title is used correctly. method_name is used for internal operations and not related to WC. It is used to map our engine codes payment methods.

Kind regards,
Wirecard Shop Systems Team

**Comment by szepeviktor** [comment]
okay @serucee
