### ISSUE TITLE
Translation of Pay Now button

### ISSUE THREAD

**Issue by josemiMontredo** [wirecard/woocommerce-ee#252]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/woocommerce-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of WooCommerce](https://github.com/wirecard/woocommerce-ee/wiki#download-wirecard-woocommerce-extension).

### Versions

**WooCommerce version:** 5.2.2
**PHP version:** 7.3.6-1+ubuntu18.04.1+deb.sury.org+1

### Issue

**Problem description:**
The payment button only says “Pay” and there is no way to translate this to something better and in a different language. 
I'm currently using Loco Translate but it doesn't detect the Pay button text so there is no way to translate it. I don't want to translate the button directly in the plugin file because if you update it, the translation will remove. 

So what can we do?
Thank you very much
...

**Comment by ucsendre** [comment]
Not an elegant solution, but you can try this if nothing else works:

`document.getElementById("seamless-submit").innerHTML = "place your custom text here";`

This line of custom js has to be executed after the page is loaded.

Ps.
The text is translated to Hungarian ("Fizetés") in version 2.0.0.

**Comment by ucsendre** [comment]
Just before the "pay now" button and the payment iframe, there is a heading which is not translated (in version 2.0.0):

`<h2 class="credit-card-heading">Enter Card Details</h2>`

Please have a look here:
https://processwire.com/docs/multi-language-support/code-i18n/#using-textdomains

**Comment by rinnhofer** [comment]
Hello @josemiMontredo ,

we are using a WooCommerce translation slug for this "Pay" button and not our own translation slug for compatibility reasons and better integration into the WooCommerce system.
Please check within Loco Translate for WooCommerce and not for Wirecard, it should be possible to translate the button there with your desired text.

Please let us know if this works out for you or if there is any other problem.

Kind regards,
Wirecard Shop Systems Team

**Comment by rinnhofer** [comment]
Hello @ucsendre ,

thank you for informing us about the missing translation. We will take a look at it and add it as soon as possible.

Kind regards,
Wirecard Shop Systems Team

**Comment by rinnhofer** [comment]
Hello,

we checked again for the missing translation, but it seems that this was already fixed in our newest version.

I hope all questions are answered, so I close this issue now. Feel free to create a new issue if something else appears.

Kind regards,
Wirecard Shop Systems Team
