### ISSUE TITLE
Template destroyed after checkout is finished

### ISSUE THREAD

**Issue by Braehler** [wirecard/woocommerce-ee#272]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/woocommerce-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of WooCommerce](https://github.com/wirecard/woocommerce-ee/wiki#download-wirecard-woocommerce-extension).

### Versions

**WooCommerce version:** ...  
**PHP version:** ...  

### Issue

**Problem description:**
When the user finished the payment via Sofort or creditcard, the user is taken back to the "thankyou.php" of woocommerce. But the template is destoyed/ not shown correctly.
This only happens with sofort or credit card. Invoice and SEPA are running well
...

**Steps to reproduce:**
Choose an article, go to the cart, go through the whole checkout process, wait for it to finish, and wait for the redirect to the thankypou.php
...

**Comment by rinnhofer** [comment]
Hello @Braehler ,

thank you for input. The processing of payments to the thank you page within our extension happens in the same way for every payment method, that is why it is suprising that the behaviour of our payment methods differs in your case.

Maybe you can give us further information about your case:
- Did you checkout with the standard theme provided by WooCommerce?
- Did you use the provided test credentials for the stated payment methods?
- Did the payment process with Sofort. and Credit Card result in a successful order?

Here are further actions you could take to get more information on what happened:
- Take a look at the logs ([Here](https://github.com/wirecard/woocommerce-ee/wiki/Debugging-and-Error-Logs) you can find the information on where to find the logs)
- Inspect the thank you page and look for javascript errors

Kind regards,
Wirecard Shop Systems Team

**Comment by tomazpu** [comment]
Hello @Braehler, 

I will close this ticket. If you have more information please reopen the issue.

Best regards, 
Wirecard Shop Systems Team
