### ISSUE TITLE
Broken image link to Wirecard logo

### ISSUE THREAD

**Issue by chesio** [wirecard/woocommerce-ee#285]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/woocommerce-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of WooCommerce](https://github.com/wirecard/woocommerce-ee/wiki#download-wirecard-woocommerce-extension).

### Versions

**WooCommerce version:** 3.7.1
**PHP version:** 5.6

### Issue

**Problem description:**

The Wirecard logo on WireCard Payment Processing and Support pages in WordPress backend does not show up, because the URL of image returns Access Denied error instead of SVG file: https://www.wirecard.com/assets/media/Logos/wirecard_dark.svg

**How to resolve:**

Just bundle the logo file with the plugin - simple and future-proof.

**Comment by serucee** [comment]
Hi @chesio ,

we actually used to have the logos bundled but this creates a lot of overhead for always changing resources. We will discuss this again internally and keep you updated. Regarding the AccessDenied - we will resolve this as soon as possible!

Best regards,
Wirecard Shop Systems Team

**Comment by serucee** [comment]
Hi @chesio ,

yes, it seems that we had some infrastructure issues that are resolved by now.

Best regards,
Wirecard Shop Systems Team
