### ISSUE TITLE
New-Order-/Thank-You-E-Mails not sent after successful authorization

### ISSUE THREAD

**Issue by bender2601** [wirecard/woocommerce-ee#334]
### Prerequisites

- [x] I have my [server set up correctly](https://github.com/wirecard/woocommerce-ee/wiki/Installation#requirements).
- [x] I am using a [supported version of WooCommerce](https://github.com/wirecard/woocommerce-ee/wiki#download-wirecard-woocommerce-extension).

### Versions

**WooCommerce version: 3.9.2  
**PHP version: 7.1  

### Issue

**Problem description:**

I have set up an appointment system with wirecard/woocommerce-wcp which stopped sending e-mail notifications (new-order-/ thank-your-notification) to admin & customer at around mid february. Due to the fact that a change to woocommerce-ee was required anyway switched these two plugins - but woocommerce is still not sending new-order-/thank-you-notifications. 

- the authorization via Wirecard/credit card is successfully completed
- after the payment the user is successfully redirected to the thank-you-page (order-overview)
- within the admin area (woocommerce > orders) the order-status is shown as "approved" / "genehmigt"

Basically everything works as it should - except that the E-Mails are not sent

I have tested it with the customer's real credentials, as well es with wirecard-test-credentials.

I have alternatively tested "invoice" & "pay by cheque" as a payment gateways which both worked fine AND did successfully send the required E-Mails.

There are also a log-entries for these wirecard-payments in woocommerce > status > log-files (they start with: _2020-03-02T12:59:19+00:00 DEBUG Wirecard_Notification_Handler::handle_notification:Notification response is instance of: Wirecard\PaymentSdk\Response\SuccessResponse_…) - I don't want to share further information here due to data privacy

**UPDATE - 2020-03-03: The problem of not sending the E-Mails only occurs, when payment action is set to "authorization", instead of "direct payment" - which might be the desired/planned behaviour in this case. Unfortunately the process of our client requires "authorization only" (payment wise), but the order to be processed (Status "processing") in woocommerce nevertheless and thank-you-/new-order-E-Mails to be sent (which worked well in the previous Plugin "WireCard WooCommerce Checkout Page").**

Thank you in advance & best regards,
Robert / Austria

...

**Steps to reproduce:**

...

**Comment by tomazpu** [comment]
Hello @bender2601 ,

thank you for your input. As you wrote in the update this is the desired behavior that emails are not sent on an authorization payment action, also the order state is custom(wc-authorization) for it. But if you want to change the behavior you can fork and adapt the plugin to your use-case.

In the file class-wc-wirecard-payment-gateway.php is a method named update_order_state() there is the logic for which order state is an order updated to, you can update the switch in the last case to processing to archive what you describe.

I hope this helped you. I will close the issue and you can reopen it if something is unclear.

Best regards,
Tomaz
