### ISSUE TITLE
UTM Return

### ISSUE THREAD

**Issue by johnnybegoodagency** [wirecard/woocommerce-ee#347]
### Prerequisites

- [ X] I have my [server set up correctly](https://github.com/wirecard/woocommerce-ee/wiki/Installation#requirements).
- [ X] I am using a [supported version of WooCommerce](https://github.com/wirecard/woocommerce-ee/wiki#download-wirecard-woocommerce-extension).

### Versions

**WooCommerce version:** 4.0  
**PHP version:** 3.1.1 

### Issue

**Problem description:**
Google Analytics does not recognize UTMs that have been sent by Google Ads or Facebook ads and displays wirecard-Payments as Source/Medium.
Paypal offers "?utm_nooverride=1" as a return URL parameter.
...

**Steps to reproduce:**

...

**Comment by tomazpu** [comment]
Hello @johnnybegoodagency, 

can u please explain in more detail what you trying to archive. If I understand correctly you want to be redirected to a URL where you want to set a parameter utm_nooverride=1 ? 
If so you can make this by editing the code and changing the redirect URL.
https://github.com/wirecard/woocommerce-ee/blob/8440d3aadf6db3a037cb3f80269e7c2a7477bc52/wirecard-woocommerce-extension/classes/includes/class-wc-wirecard-payment-gateway.php#L314

I hope this helps you but if you have any other questions feel free to reply. 
Best regards, 
Tomaz

**Comment by johnnybegoodagency** [comment]
Hi Tomaz!
?utm_nooverride is a function that paypal offers, I dont think this will help in this case.

The issue we are facing:

we are sending customers to our show via Google Ads. When they click on an add, we send variables in the URL, that make tracking via Google Analytics possible.
E.g.: myurl.com/?utm_source=google&utm_campaign=mycampaign
In Google Analytics we can then see, where our customers came from, when they bought something in our store – in this case the source is Google Ads and a specific campaign.

Now when they go through wirecard we face the problem, that these parameters get lost and the referral source is either wirecard itself or the payment provider they use (sometimes even the bank the user checks out with).

So we need a solution like paypals utm_nooverride to ensure, that the referrals stay what we inputed.

**Comment by tomazpu** [comment]
Hi @johnnybegoodagency, 

I think now I understand. I suggest contacting our support at:
Phone: +61 1300 599 991
Email: shop-systems-support@wirecard.com

as they will be able to help you better. They can analyze the behavior with you and pinpoint where the data gets lost (wich module) so that it can be fixed. 

Best regards,
Tomaz

**Comment by johnnybegoodagency** [comment]
Hi Tomaz!
Thanks, will do so.
Best, Flo
