### ISSUE TITLE
Plugin para wordpress

### ISSUE THREAD

**Issue by DesarrolloInteratec** [wirecard/woocommerce-ee#64]
Hola buenos dias, llevo dias intentando instalar la funcionalidad de wirecard para woocommerce de wordpress, el plugin me va fallo y se bloquea la web tengo que entrar por ftp para poder quitar el plugin.

Me podria ayudar?

La versión de woocommerce es 3.3.5

y la de wordpress 4.9.5

Un saludo, gracias.

**Comment by DesarrolloInteratec** [comment]
Hola losiento pero no funciona, me muestra el mismo error , se desactiva la web y no se puede mostrar.
tengo que tener algun otro plugin instalado?
Un saludo, gracias.

**Comment by jakubpolomsky** [comment]
Hello,

Would you please contact us via our support? I would need some more informations and it will be easier in a phone call or emails. [shop-systems-support@wirecard.com](mailto:shop-systems-support@wirecard.com) It is possible that we'll ask for an access to your system for that.

Thank you!
